import React, { Component, useState } from 'react';
import Head from "next/head";
import Layout from "@/component/layouts/Layout";
import { Box, Button, Dialog } from "@mui/material";
import Typography from '@mui/material/Typography';
import ReportsoneTabal from '@/component/ReportsAgents/ReportsAgentsOneTabal';
import DealsAgentsTabal from '@/component/DealsAgents/DealsAgentsTabal';
import DateAndSelect from '@/component/dashboard/DateAndSelect';

export default function Dealsagents() {
  //pop//
  const [open, setOpen] = React.useState(false);

  const handleClickOpen = () => {
    setOpen(true);
  };

  const handleClose = () => {
    setOpen(false);
  };
  return (
    <>
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <Box>
            <Box className="tabl_p_btn_v2">
              <Typography className="def_had_txt">Deals (for agents)</Typography>
              <Button onClick={handleClickOpen}>Add Player</Button>
            </Box>
            <DateAndSelect />
            <DealsAgentsTabal />
          </Box>
        </div>
        <Dialog
          open={open}
          onClose={handleClose}
          aria-labelledby="alert-dialog-title"
          aria-describedby="alert-dialog-description"
          className='def_modal dilog settlements_modl'
        >
          <Box>
            <Box className="sign">
              <Box className="sign_min">
                <Typography component={"h2"} className='def_h2_hd mrg_colr'>Add Player</Typography>
                <Box className="flx_log_input">
                  <Box component="form">
                    <Box className="input-box">
                      <input
                        type="text"
                        id="username"
                        name="username"
                        autoComplete="username"
                        placeholder="User id"
                        autoFocus
                        className="user-input"
                      />
                    </Box>
                  </Box>
                  <Button className='def_btn'>Add</Button>
                </Box>

              </Box>
            </Box>
          </Box>
        </Dialog>
      </Layout>
    </>
  );
}
