import React, { Component, useState } from 'react';
import Head from "next/head";
import Layout from "@/component/layouts/Layout";
import { Box, Grid } from "@mui/material";
import Typography from '@mui/material/Typography';
import ReportsoneTabal from '@/component/ReportsAgents/ReportsAgentsOneTabal';
import DealsAgentsTabal from '@/component/DealsAgents/DealsAgentsTabal';

export default function Dealsagents() {

  return (
    <>
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <Box>
            <Typography className="def_had_txt">Deals (for agents)</Typography>
            {/* <DateAndSelect /> */}
            <DealsAgentsTabal />
          </Box>
        </div>
      </Layout>
    </>
  );
}
