import React, { Component, useEffect, useState } from "react";
import Head from "next/head";
import Layout from "@/component/layouts/Layout";
import { Box, Grid } from "@mui/material";
import Typography from "@mui/material/Typography";
import DateAndSelect, { Filters } from "@/component/dashboard/DateAndSelect";
import ClubResultsTabal from "@/component/dashboard/ClubResultsTabal";
import PlayerResultsTabal from "@/component/dashboard/PlayerResultsTabal";
import NicknameResultsTabal from "@/component/dashboard/NicknameResultsTabal";
import { useRouter } from "next/router";
import { useToken } from "../hooks/get-user-login-status";
import PlayerIncome from "@/component/dashboard/player-income";
import {
  currentDateInFormat,
  getDateOfBeforeOneMonthInFormat,
} from "@/utils/get-date";
import {
  EndpointUrl,
  endpointUrls,
  getLocalStorage,
  getRecords,
  LocalStorageKeys,
} from "@/helper";
import { AgentResults } from "@/types/player-income";
import { generateUrl } from "@/helper/_api_wrapper";

export interface AgentAggregateRecord {
  title: string;
  price: string;
  currency: string;
}

export interface AgentIncomeResult {
  title: string;
  data: AgentAggregateRecord[];
}

export default function Dashboard() {
  const [token, setToken] = useToken();
  const [filters, setFilters] = useState<Filters>();
  const [dashboardAggregateResult, setDashboardAggregateResult] = useState<
    AgentIncomeResult[]
  >([]);

  const _router = useRouter();

  const resultArray: AgentIncomeResult[] = [];

  const agentIncomeArray: AgentAggregateRecord[] = [];
  const playerResultsArray: AgentAggregateRecord[] = [];
  const agentEarningsArray: AgentAggregateRecord[] = [];

  useEffect(() => {
    console.log("dashboard aggregate result", dashboardAggregateResult);
    if (dashboardAggregateResult.length) {
      setDashboardAggregateResult([]);
    }
    getPlayerIncome();
  }, [filters]);

  const getPlayerIncome = () => {
    getRecords(generateUrl(endpointUrls[EndpointUrl.AGENT_RESULTS]))
      .then((response: AgentResults) => {
        for (const [key, value] of Object.entries(response)) {
          if (key.startsWith("_agent_")) {
            if (
              key === "_agent_earnings_rb" ||
              key === "_agent_earnings_rebate" ||
              key === "_agent_earnings"
            ) {
              agentEarningsArray.push({
                title: key,
                price: value,
                currency: "$",
              });
            } else {
              agentIncomeArray.push({
                title: key,
                price: value,
                currency: "$",
              });
            }
          } else if (key.startsWith("_player")) {
            playerResultsArray.push({
              title: key,
              price: value,
              currency: "$",
            });
          }
        }

        if (agentIncomeArray.length > 0) {
          resultArray.push({ title: "Agent Income", data: agentIncomeArray });
        }
        if (playerResultsArray.length > 0) {
          resultArray.push({
            title: "Player Results",
            data: playerResultsArray,
          });
        }
        if (agentEarningsArray.length > 0) {
          resultArray.push({
            title: "Agent Earnings",
            data: agentEarningsArray,
          });
        }
        setDashboardAggregateResult(resultArray);
      })
      .catch((e) => {
        // [TODO] set the mock data for the response of the agency results data
        // setPlayerIncomeData(mockPlayerIncome);
        console.log("error while fetching agent results records:", e);
      });
  };

  useEffect(() => {
    if (!token) {
      _router.push("/login");
    }
  }, [token]);

  const handleFilterChange = (filters: any) => {
    setFilters(filters);
  };

  return (
    <Layout>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Box>
          <Typography className="def_had_txt">Summary</Typography>
          <DateAndSelect onFilterChange={handleFilterChange} />
          <Box className="graph_bx">
            <Typography className="graph_bx_p">
              Player | Agent earnings
            </Typography>
            <img src="img/graph_img_01.png" alt="" />
          </Box>
          {/** Players Income */}
          {dashboardAggregateResult.map((item: AgentIncomeResult, index) => (
            <PlayerIncome key={item.title} data={item} />
          ))}
          {/** Players Income End */}
          <PlayerResultsTabal />
          <ClubResultsTabal />
          {/* <NicknameResultsTabal /> */}
        </Box>
      </div>
    </Layout>
  );
}
