import React, { Component, useState } from 'react';
import Head from "next/head";
import Layout from "@/component/layouts/Layout";
import { Box, Grid } from "@mui/material";
import Typography from '@mui/material/Typography';
import DateAndSelect from '@/component/dashboard/DateAndSelect';
import ClubResultsTabal from '@/component/dashboard/ClubResultsTabal';
import PlayerResultsTabal from '@/component/dashboard/PlayerResultsTabal';
import NicknameResultsTabal from '@/component/dashboard/NicknameResultsTabal';

export default function Dashboard() {

  return (
    <>
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <Box>
            <Typography className="def_had_txt">Summary</Typography>
            <DateAndSelect />
            <Box className="graph_bx">
              <Typography className="graph_bx_p">Player | Agent earnings</Typography>
              <img src="img/graph_img_01.png" alt="" />
            </Box>
            {/* <Box className="graph_bx graph_bx_v2">
              <Typography className="graph_bx_p">App Report</Typography>
              <img src="img/graph_img_02.png" alt="" />
            </Box> */}
            <Box sx={{ mt: '25px' }}>
              <Typography className='agent_p'>Agent income</Typography>
              <Grid container spacing={[3, 3, 3]} className='selct_grid'>
                <Grid item xs={6} md={3} xl={2} >
                  <Box className='agent_income'>
                    <Typography>Profit/Loss in USD</Typography>
                    <Typography component="h3" className=''>$ 60,319,23</Typography>
                  </Box>
                </Grid>
                <Grid item xs={6} md={3} xl={2} >
                  <Box className='agent_income'>
                    <Typography>Rake in USD</Typography>
                    <Typography component="h3" className=''>$ 9,705.77</Typography>
                  </Box>
                </Grid>
                <Grid item xs={6} md={3} xl={2} >
                  <Box className='agent_income'>
                    <Typography>Rackeback in USD</Typography>
                    <Typography component="h3" className=''>$ 9,705.77</Typography>
                  </Box>
                </Grid>
                <Grid item xs={6} md={3} xl={2} >
                  <Box className='agent_income'>
                    <Typography>Rebate in USD</Typography>
                    <Typography component="h3" className=''>$ -1.000,00</Typography>
                  </Box>
                </Grid>
                <Grid item xs={6} md={3} xl={2} >
                  <Box className='agent_income'>
                    <Typography>Agent Settlement In Sum</Typography>
                    <Typography component="h3" className=''>$ 56,829.90</Typography>
                  </Box>
                </Grid>
              </Grid>
            </Box>

            <Box className='play_min_bx_set'>
              <Typography className='agent_p'>Players income</Typography>
              <Grid container spacing={[3, 3, 3]} className='selct_grid'>
                <Grid item xs={6} md={3} xl={2} >
                  <Box className='agent_income'>
                    <Typography>Profit/Loss in USD</Typography>
                    <Typography component="h3" className=''>$ 60,319,23</Typography>
                  </Box>
                </Grid>
                <Grid item xs={6} md={3} xl={2} >
                  <Box className='agent_income'>
                    <Typography>Rake in USD</Typography>
                    <Typography component="h3" className=''>$ 9,705.77</Typography>
                  </Box>
                </Grid>
                <Grid item xs={6} md={3} xl={2} >
                  <Box className='agent_income'>
                    <Typography>Rackeback in USD</Typography>
                    <Typography component="h3" className=''>$ 9,705.77</Typography>
                  </Box>
                </Grid>
                <Grid item xs={6} md={3} xl={2} >
                  <Box className='agent_income'>
                    <Typography>Rebate in USD</Typography>
                    <Typography component="h3" className=''>$ -1.000,00</Typography>
                  </Box>
                </Grid>
                <Grid item xs={6} md={3} xl={2} >
                  <Box className='agent_income'>
                    <Typography>Agent Settlement In Sum</Typography>
                    <Typography component="h3" className=''>$ 56,829.90</Typography>
                  </Box>
                </Grid>
              </Grid>
            </Box>
            <Box className=''>
              <Typography className='agent_p'>Agent earnings</Typography>
              <Grid container spacing={[3, 3, 3]} className='selct_grid'>
                <Grid item xs={6} md={3} xl={2} >
                  <Box className='agent_income'>
                    <Typography>Profit/Loss in USD</Typography>
                    <Typography component="h3" className=''>$ 60,319,23</Typography>
                  </Box>
                </Grid>
                <Grid item xs={6} md={3} xl={2} >
                  <Box className='agent_income'>
                    <Typography>Rake in USD</Typography>
                    <Typography component="h3" className=''>$ 9,705.77</Typography>
                  </Box>
                </Grid>
                <Grid item xs={6} md={3} xl={2} >
                  <Box className='agent_income'>
                    <Typography>Rackeback in USD</Typography>
                    <Typography component="h3" className=''>$ 9,705.77</Typography>
                  </Box>
                </Grid>
                <Grid item xs={6} md={3} xl={2} >
                  <Box className='agent_income'>
                    <Typography>Rebate in USD</Typography>
                    <Typography component="h3" className=''>$ -1.000,00</Typography>
                  </Box>
                </Grid>
                <Grid item xs={6} md={3} xl={2} >
                  <Box className='agent_income'>
                    <Typography>Agent Settlement In Sum</Typography>
                    <Typography component="h3" className=''>$ 56,829.90</Typography>
                  </Box>
                </Grid>
              </Grid>
            </Box>

            <PlayerResultsTabal />
            <ClubResultsTabal/>
            <NicknameResultsTabal />
          </Box>
        </div>
      </Layout>
    </>
  );
}
