import ReportsAgentsOne from "@/component/ReportsAgents/ReportsAgentsOneTabal";
import ResultsTable from "@/component/ReportsAgents/ResultsTable";
import DateAndSelect, { Filters } from "@/component/dashboard/DateAndSelect";
import Layout from "@/component/layouts/Layout";
import { Box } from "@mui/material";
import Typography from "@mui/material/Typography";
import Head from "next/head";
import { useState } from "react";

export default function ReportsAgents() {
  const [filters, setFilters] = useState<Filters>();
  const onFilterChanged = (filter: Filters) => {
    setFilters(filter);
  };

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Box>
          <Typography className="def_had_txt">Reports (for agents)</Typography>
          <DateAndSelect onFilterChange={onFilterChanged} />
          <ReportsAgentsOne filters={filters} />
          <ResultsTable filters={filters} />
        </Box>
      </div>
    </Layout>
  );
}
