import React, { Component, useState } from 'react';
import Head from "next/head";
import Layout from "@/component/layouts/Layout";
import { Box, Button, Grid, Modal } from "@mui/material";
import Typography from '@mui/material/Typography';
import moment from 'moment';
import Select, { SelectChangeEvent } from '@mui/material/Select';
import "bootstrap/dist/css/bootstrap.css";
import "bootstrap-daterangepicker/daterangepicker.css";
import DateRangePicker from 'react-bootstrap-daterangepicker';
import FormControl from '@mui/material/FormControl';
import KeyboardArrowDownIcon from '@mui/icons-material/KeyboardArrowDown';
import MenuItem from '@mui/material/MenuItem';
import Dialog from '@mui/material/Dialog';
import SettingsOneTabal from '@/component/Settings/SettingsOneTabal';
import DateAndSelect from '@/component/dashboard/DateAndSelect';



export default function Settlements() {
  const [age, setAge] = React.useState('');

  const handleChange = (event: SelectChangeEvent) => {
    setAge(event.target.value);
  };

  //datepicker
  const [fromDate, setFromDate] = useState(new Date());
  const [toDate, setToDate] = useState(new Date());
  const range = {
    Today: [moment(), moment()],
    Yesterday: [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
    'Last 7 Days': [moment().subtract(6, 'days'), moment()],
    'Last 30 Days': [moment().subtract(29, 'days'), moment()],
    'This Month': [moment().startOf('month'), moment().endOf('month')],
    'Last Month': [
      moment().subtract(1, 'month').startOf('month'),
      moment().subtract(1, 'month').endOf('month'),
    ],
    'Last Year': [
      moment().subtract(1, 'year').startOf('year'),
      moment().subtract(1, 'year').endOf('year'),
    ],
  };

  const handleEvent = (event: any, picker: any) => {
    setFromDate(picker.startDate._d.toISOString());
    setToDate(picker.endDate._d.toISOString());
  };

  
  return (
    <>
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <Box>
            <Box className="tabl_p_btn_v2">
              <Typography className="def_had_txt">Settings</Typography>
              
            </Box>
            <DateAndSelect />

            <Box className="user_info_min" >              
              <Typography component="h2" className=''>User information</Typography>
              <Box className="user_info_conti">
                <Typography>Username</Typography>
                <span>tellmewhyy</span>
              </Box>
              <Box className="user_info_conti">
                <Typography>Id</Typography>
                <span>2100559</span>
              </Box>
              <Box className="user_info_conti">
                <Typography>Type </Typography>
                <span>Agent</span>
              </Box>
              <Box className="user_info_conti">
                <Typography>Agent name</Typography>
                <span>Ferrranito</span>
              </Box>
            </Box>
            {/* <SettingsOneTabal /> */}
          </Box>
        </div>
      </Layout>


      



    </>
  );
}
